# Autorise les fichiers individuels jusqu'à 500 Mo (ou met -1 pour illimité, mais 500MB est plus sûr)
spring.servlet.multipart.max-file-size=500MB
# Autorise la requête totale jusqu'à 500 Mo
spring.servlet.multipart.max-request-size=500MB